
export default [
  {path:'/',component:()=>import('./components/index.vue'),name: "index"},
  {path:'/profile',component:()=>import('./components/profile.vue'),name: "profile"},
  // {path:'/tanxin',component:tanxin,name: "tanxin"},
  {path:'/liaoxing',component:() =>import('./components/liaoxing.vue'),name: "liaoxing"},
  {path:'/news',component:() =>import('./components/news/news.vue'),name: "news"},
  {path:'/news1',component:()=>import('./components/news/news1.vue'),name: "news1"},
  {path:'/news2',component:()=>import('./components/news/news2.vue'),name: "news2"},
  {path:'/news3',component:()=>import('./components/news/news3.vue'),name: "news3"},
  {path:'/news4',component:()=>import('./components/news/news4.vue'),name: "news4"},
  {path:'/news5',component:()=>import('./components/news/news5.vue'),name: "news5"},
  {path:'/news6',component:()=>import('./components/news/news6.vue'),name: "news6"},
  {path:'/news7',component:()=>import('./components/news/news7.vue'),name: "news7"},
  {path:'/news8',component:()=>import('./components/news/news8.vue'),name: "news8"},
  {path:'/news9',component:()=>import('./components/news/news9.vue'),name: "news9"},
  {path:'/news10',component:()=>import('./components/news/news10.vue'),name: "news10"},
  {path:'/news11',component:()=>import('./components/news/news11.vue'),name: "news11"},
  {path:'/news12',component:()=>import('./components/news/news12.vue'),name: "news12"},
  {path:'/news13',component:()=>import('./components/news/news13.vue'),name: "news13"},
  {path:'/news14',component:()=>import('./components/news/news14.vue'),name: "news14"},
  {path:'/design',component:()=>import('./components/design.vue'),name: "design"},
  {path:'/python',component:()=>import('./components/python.vue'),name: "python"},
  {path:'/web',component:()=>import('./components/web.vue'),name: "web"},
  {path:'/wx',component:()=>import('./components/wx.vue'),name: "wx"},
  {path:'/data',component:()=>import('./components/data.vue'),name: "data"},
  {path:'/data_global',component:()=>import('./components/data_global.vue'),name: "data_global"},
  {path:'/data_3d',component:()=>import('./components/data_3d.vue'),name: "data_3d"},
  {path:'/show',component:()=>import('./components/show.vue'),name: "show"},
  {path:'/seo',component:()=>import('./components/seo.vue'),name: "seo"},
  // {path:'/1',component:helloworld,name: "helloworld"},
  {path:'*',redirect:"/"}
]